# Generated by Django 4.2.3 on 2023-07-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokenMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_author', models.CharField(max_length=40, verbose_name='اپراتور ثبت')),
                ('material_name', models.CharField(max_length=300, verbose_name='نام')),
                ('material_code', models.CharField(max_length=50, verbose_name='کد')),
                ('material_color', models.CharField(max_length=50, verbose_name='رنگ')),
                ('material_quantity', models.PositiveIntegerField(null=True, verbose_name='موجودی')),
                ('material_location', models.CharField(max_length=50, verbose_name='انبار')),
                ('material_hall', models.CharField(max_length=20, verbose_name='سالن انبار')),
                ('material_unit', models.CharField(max_length=20, verbose_name='واحد')),
                ('material_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان دقیق ثبت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('is_available', models.BooleanField(default=True, verbose_name='موجودی / عدم موجودی')),
                ('row', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'خرابی ماده اولیه',
                'verbose_name_plural': 'خرابی مواد اولیه',
            },
        ),
        migrations.CreateModel(
            name='BrokenProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_author', models.CharField(max_length=40, verbose_name='اپراتور ثبت')),
                ('product_name', models.CharField(max_length=300, verbose_name='نام کالا')),
                ('product_code', models.CharField(max_length=50, verbose_name='کد کالا')),
                ('product_color', models.CharField(max_length=50, verbose_name='رنگ کالا')),
                ('product_quantity', models.PositiveIntegerField(null=True, verbose_name='موجودی کالا')),
                ('product_location', models.CharField(max_length=50, verbose_name='انبار کالا')),
                ('product_hall', models.CharField(max_length=20, verbose_name='سالن انبار کالا')),
                ('product_unit', models.CharField(max_length=20, verbose_name='واحد')),
                ('product_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان دقیق ثبت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('is_available', models.BooleanField(default=True, verbose_name='موجودی / عدم موجودی')),
                ('row', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'خرابی کالا',
                'verbose_name_plural': 'خرابی کالاها',
            },
        ),
        migrations.CreateModel(
            name='ReturnedMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_author', models.CharField(max_length=40, verbose_name='اپراتور ثبت')),
                ('material_name', models.CharField(max_length=300, verbose_name='نام')),
                ('material_code', models.CharField(max_length=50, verbose_name='کد')),
                ('material_color', models.CharField(max_length=50, verbose_name='رنگ')),
                ('material_quantity', models.PositiveIntegerField(null=True, verbose_name='موجودی')),
                ('material_location', models.CharField(max_length=50, verbose_name='انبار')),
                ('material_hall', models.CharField(max_length=20, verbose_name='سالن انبار')),
                ('material_unit', models.CharField(max_length=20, verbose_name='واحد')),
                ('material_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان دقیق ثبت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('is_available', models.BooleanField(default=True, verbose_name='موجودی / عدم موجودی')),
                ('row', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ماده اولیه مرجوعی',
                'verbose_name_plural': 'مواد اولیه مرجوعی',
            },
        ),
        migrations.CreateModel(
            name='ReturnedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_author', models.CharField(max_length=40, verbose_name='اپراتور ثبت')),
                ('product_name', models.CharField(max_length=300, verbose_name='نام کالا')),
                ('product_code', models.CharField(max_length=50, verbose_name='کد کالا')),
                ('product_color', models.CharField(max_length=50, verbose_name='رنگ کالا')),
                ('product_quantity', models.PositiveIntegerField(null=True, verbose_name='موجودی کالا')),
                ('product_location', models.CharField(max_length=50, verbose_name='انبار کالا')),
                ('product_hall', models.CharField(max_length=20, verbose_name='سالن انبار کالا')),
                ('product_unit', models.CharField(max_length=20, verbose_name='واحد')),
                ('product_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان دقیق ثبت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('is_available', models.BooleanField(default=True, verbose_name='موجودی / عدم موجودی')),
                ('row', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'کالای مرجوعی',
                'verbose_name_plural': 'کالاهای مرجوع شده',
            },
        ),
    ]
